---
title: "Curating key wastewater taxa genome assemblies"
format: html
editor: source
tbl-cap-location: top
execute:
  echo: false 
  warning: false
  message: false
params:
  system_type: "swbd"
---

```{r load_packages}
library(tidyverse)
library(rentrez)
library(xml2)
```

```{r read_blastn_results}
root_dir <- "/Users/shaman.narayanasamy/Work/Data/key_taxa_ww/extracted sequences of core bacteria/NCBI_taxonomy_limited_blastn_results/"

files <- 
  list.files(root_dir) %>% .[grep(params$system_type, .)]


  for (i in 1:length(files)){ 
  
  tmp <- read_tsv(paste0(root_dir, files[i]), comment = "#", 
                      col_names =   
                        c("query acc.ver", "subject acc.ver", "% identity", 
                          "alignment length", "mismatches", "gap opens", "q. start", 
                          "q. end", "s. start", "s. end", "evalue", "bit score")) %>% 
    mutate(taxa = files[i]) %>% 
    separate(taxa, into = c("system", "taxonomic_level", "tmp0", "taxa"), sep = "_") %>% 
    select(-tmp0) %>%  
    head(n = 100) 
 if (i == 1) {  
   blast_dat <- tmp } else { 
    blast_dat <- bind_rows(blast_dat, tmp) } 
}

```
```{r function_get_assembly_id}
# Function: Searches for links to any assemblies within the NCBI based on a given
# query ID

get_assembly_id <- function(subject_id =
"JAKIHP010000012.1"){ 
  
  nuccore2assemblylinks <- entrez_link(dbfrom = "nuccore", db = "assembly", id = subject_id)  
 
  if (is.null(nuccore2assemblylinks$links$nuccore_assembly) ||
      length(nuccore2assemblylinks$links$nuccore_assembly) == 0) {
   
    return(NA)
    
  } else {
    
  nuccore2assemblylinks$links$nuccore_assembly %>%   
    entrez_summary(db = "assembly", id = .) %>%  
    .$assemblyaccession %>% 
    return()
  }
}
```

```{r extract_related_assemblies, eval = F}
# Create an empty column
blast_dat$assembly_id = NA

# Loop through the table
for (i in 1:nrow(blast_dat)){
  blast_dat$assembly_id[i] <- get_assembly_id(subject_id = blast_dat$`subject acc.ver`[i])
}

## Those assemblies that represent MAGs are somehow different and their IDs do
## not link to an assembly. Therefore, we need to manipulate the BLAST subject
## ID to extract the "root" ID and then repeat the search on the root assembly ID
blast_dat <- blast_dat %>% 
  mutate(change = `subject acc.ver`) %>% #select(`subject acc.ver`, change) %>% 
  separate(change, into = c("id_root", "to_change"), sep = "010") %>% 
  mutate(id_root = paste0(id_root, "010")) %>% # replace the lost 010 that was removed
  separate(to_change, into = "tmp", sep = '\\.') %>% 
  mutate(replaced_suffix = str_replace_all(tmp, "[1-9]", "0")) %>% 
  mutate(root_assembly_id = paste0(id_root, replaced_suffix)) %>% 
  select(-c(id_root, tmp, replaced_suffix)) %>% 
  mutate(is_mag = case_when(
            is.na(assembly_id) ~ TRUE,
            TRUE ~ FALSE)
  )
 
# Loop through the table, this time with the root assembly IDs
for (i in 1:nrow(blast_dat)){
  if (is.na(blast_dat$assembly_id[i])){ 
    blast_dat$assembly_id[i] <- get_assembly_id(subject_id = blast_dat$root_assembly_id[i])
  } else {
    print ("All good!")
    }
}

## Identify some edge cases and solve them
blast_dat <- blast_dat %>% filter(is.na(assembly_id)) %>%
  mutate(root_assembly_id = str_remove(`subject acc.ver`, "\\.1$")) %>% # Remove .1 suffix
  mutate(root_assembly_id = str_sub(root_assembly_id, 1, nchar(root_assembly_id)-4)) %>% # Keep all but last 4 digits
  mutate(root_assembly_id = paste0(root_assembly_id, "0000")) %>% # Append four zeros
  bind_rows(blast_dat %>% filter(!is.na(assembly_id)), .)

## Rerun the extraction of assembly IDs
for (i in 1:nrow(blast_dat)){
  if (is.na(blast_dat$assembly_id[i])){ 
    blast_dat$assembly_id[i] <- get_assembly_id(subject_id = blast_dat$root_assembly_id[i])
  } else {
    print ("All good!")
    }
}
```



```{r write_table, eval = F}
blast2assembly <- 
  blast_dat %>% filter(!is.na(assembly_id)) %>%
  write_tsv(
    paste("/Users/shaman.narayanasamy/Work/Data/key_taxa_ww/extracted sequences of core bacteria/assembly_information/", paste0(params$system_type, "_blast2assembly.tsv"), sep = "")
    )

blast2assembly %>% select(assembly_id, taxonomic_level, taxa) %>% distinct() %>%  
  write_tsv(
    paste("/Users/shaman.narayanasamy/Work/Data/key_taxa_ww/extracted sequences of core bacteria/assembly_information/", paste0(params$system_type, "_assembly_list.tsv"), sep = "")
    )
```

```{r}
blast2assembly <- 
    read_tsv(
    paste("/Users/shaman.narayanasamy/Work/Data/key_taxa_ww/extracted sequences of core bacteria/assembly_information/", paste0(params$system_type, "_blast2assembly.tsv"), sep = "")
    )
```



```{r link_genomes_to_taxonomy, eval = F}
# Check if 'blast2assembly2taxonomy' exists, if not, initialize it
if(!exists("blast2assembly2taxonomy")) {
  blast2assembly2taxonomy <- tibble(root_assembly_id = character(), taxid = character(), lineage = character())
}

root_assembly_ids <- blast2assembly %>% 
  select(root_assembly_id) %>% 
  distinct() %>% 
  pull(root_assembly_id)


for (i in root_assembly_ids) { 
  # Check if the current root_assembly_id has already been processed
  if(!(i %in% blast2assembly2taxonomy$root_assembly_id)) {
    tryCatch({
      tmp_summary <- entrez_summary(id = i, db = "nuccore")
      tmp_fetch <- entrez_fetch(id = tmp_summary$taxid, db = "taxonomy", rettype = "xml")
      tmp_lineage <- xml_find_all(read_xml(tmp_fetch), ".//Lineage") %>% xml_text()
      
      # Temporarily store the results
      tmp_tibble <- tibble(root_assembly_id = i, taxid = as.character(tmp_summary$taxid), lineage = tmp_lineage)
      
      # Bind the results to the main dataframe
      blast2assembly2taxonomy <- bind_rows(blast2assembly2taxonomy, tmp_tibble)
      
    }, error = function(e) {
      message("Error processing ", i, ": ", e$message)
    })
  }
}

## Since the root assembly ID does not work, we use an alternative ID, i.e. the contig ID of the blast subject.
alternative_ids <- 
filter(blast2assembly, !root_assembly_id %in% blast2assembly2taxonomy$root_assembly_id) %>% 
  select(`subject acc.ver`, root_assembly_id)

for (i in 1:length(alternative_ids$`subject acc.ver`)){ 
 
  subject_id = alternative_ids$`subject acc.ver`[i]

  tmp_summary <- entrez_summary(id = subject_id, db = "nuccore")
  
  tmp_fetch <- entrez_fetch(id = tmp_summary$taxid, db = "taxonomy", rettype = "xml")
  
  tmp_lineage <- xml_find_all(tmp_fetch %>% read_xml(), ".//Lineage") %>% xml_text()
  
  if(i == 1){
    tmp_alt <-  
      bind_cols(`root_assembly_id` = alternative_ids$root_assembly_id[i], taxid = as.character(tmp_summary$taxid), lineage = tmp_lineage)
  } else {
  tmp_alt <- 
  bind_rows(tmp_alt,  
            bind_cols(`root_assembly_id` = alternative_ids$root_assembly_id[i], taxid = as.character(tmp_summary$taxid), lineage = tmp_lineage))
  }
  rm(tmp_summary, tmp_fetch, tmp_lineage)
}

## Clean up the lineage text
blast2assembly2taxonomy <- 
  bind_rows(tmp_alt, blast2assembly2taxonomy) %>% 
  mutate(lineage = str_remove_all(lineage, pattern = 'cellular organisms; '))
```

```{r write_taxonomy_inoformation, eval = F}
blast2assembly2taxonomy_all <- 
  left_join(blast2assembly, blast2assembly2taxonomy, by = "root_assembly_id")

write_tsv(blast2assembly2taxonomy_all,  
          paste("/Users/shaman.narayanasamy/Work/Data/key_taxa_ww/extracted sequences of core bacteria/assembly_information/", paste0(params$system_type, "_blast2assembly2taxonomy.tsv"), sep = "") 
          )

blast2assembly2taxonomy_all %>% 
  filter(`% identity` >= 95) %>% 
write_tsv(paste("/Users/shaman.narayanasamy/Work/Data/key_taxa_ww/extracted sequences of core bacteria/assembly_information/", paste0(params$system_type, "_blast2assembly2taxonomy-95%identity.tsv"), sep = "") 
          )

blast2assembly2taxonomy_all %>% 
  filter(`% identity` >= 95) %>% select(`query acc.ver`) %>% distinct()
```

```{r read_taxonomy_information}
blast2assembly2taxonomy_all <- 
bind_rows(
  read_tsv("/Users/shaman.narayanasamy/Work/Data/key_taxa_ww/extracted sequences of core bacteria/assembly_information/sb_blast2assembly2taxonomy.tsv"),
  read_tsv("/Users/shaman.narayanasamy/Work/Data/key_taxa_ww/extracted sequences of core bacteria/assembly_information/swbd_blast2assembly2taxonomy.tsv")
)
```
```{r define_refined_taxonomy, fig.height=6, fig.width=8}
set.seed(125) # Setting a seed for reproducibility

# Split to a refine taxonomy information table
refined_taxonomy_info <- 
  blast2assembly2taxonomy_all %>% 
  select(assembly_id, lineage, taxa, system) %>% 
  distinct() %>% 
  separate(lineage, into = c( 
    "kingdom",
    "phylum",
    "class",
    "order",
    "family",
    "genus",
    "species"), fill = "right", sep = '; ', remove = F) %>% 
  mutate_at(vars(c( 
    "kingdom",
    "phylum",
    "class",
    "order",
    "family",
    "genus",
    "species")), as.factor) %>% 
  mutate(genus = factor(genus, levels = sample(levels(.$genus))))
```


```{r plot_detailed_taxonomy, fig.height=6, fig.width=8}
refined_taxonomy_info %>% 
  ggplot(aes(x = taxa, fill = genus))+
  geom_bar() +
  facet_wrap(~ system, scale = "free_x") +
  theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "right") +
  xlab("Host taxa based on 16S assignment") +
  scale_fill_viridis_d(option = "D", begin = 0, end = 1, direction = 1, name = "Lineage") + # Discrete color scale for lineage
  guides(fill = guide_legend(ncol = 1, title = "Host lineage based on NCBI"))
```


```{r plot_taxonomy, fig.height=5, fig.width=5}
# Create a named list for the Venn diagram
venn_list <- list(
  sb = refined_taxonomy_info %>% filter(system == "sb") %>% pull(lineage) %>% unique(),
  swbd = refined_taxonomy_info %>% filter(system == "swbd") %>% pull(lineage) %>% unique()
)

# Find the intersection manually to ensure there is overlap
common_ids <- Reduce(intersect, venn_list)
length(common_ids)  # 0 if there is no overlap

# Generate the Venn diagram with the cleaned data
ggvenn(venn_list, stroke_color = NA, auto_scale = T)
```


